language: node_js
sudo: required
before_script:
- npm install -g bower polymer-cli
- bower install
- polymer lint --input paper-buttons-group.html
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- polymer test
dist: trusty
