language: node_js
sudo: required
before_script:
- npm install -g bower polymer-cli
- bower install
- polymer lint --input paper-buttons-group.html --rules=polymer-2
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- polymer test
dist: trusty
